language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
env:
 - ES_VERSION=0.90.0
 - ES_VERSION=0.90.1
 - ES_VERSION=0.90.2
 - ES_VERSION=0.90.3
 - ES_VERSION=0.90.4
 - ES_VERSION=0.90.5

install: "cpanm --installdeps --notest ."
script:  "./run_travis_tests.sh"
